name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
permissions: 
  contents: write


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install

      - name: Build the website
        run: |
          yarn docs:build
          cd docs/.vitepress/dist

      - name: Deploy to gh-pages branch
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: docs/.vitepress/dist

        
